// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: helloworld.proto

// grpc中的proto文件中 package 里面的.v1一般是什么意思

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-125_time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Greeter_SayHello_FullMethodName = "/proto.v1.Greeter/SayHello"
)

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeterClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, Greeter_SayHello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
// All implementations must embed UnimplementedGreeterServer
// for forward compatibility
type GreeterServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedGreeterServer()
}

// UnimplementedGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (UnimplementedGreeterServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreeterServer) mustEmbedUnimplementedGreeterServer() {}

// UnsafeGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServer will
// result in compilation errors.
type UnsafeGreeterServer interface {
	mustEmbedUnimplementedGreeterServer()
}

func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {
	s.RegisterService(&Greeter_ServiceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Greeter_ServiceDesc is the grpc.ServiceDesc for Greeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.v1.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld.proto",
}

const (
	OfficialAccount_GetOfficialAccount_FullMethodName = "/proto.v1.OfficialAccount/GetOfficialAccount"
)

// OfficialAccountClient is the client API for OfficialAccount service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OfficialAccountClient interface {
	GetOfficialAccount(ctx context.Context, in *OfficialAccountRequest, opts ...grpc.CallOption) (*OfficialAccountReply, error)
}

type officialAccountClient struct {
	cc grpc.ClientConnInterface
}

func NewOfficialAccountClient(cc grpc.ClientConnInterface) OfficialAccountClient {
	return &officialAccountClient{cc}
}

func (c *officialAccountClient) GetOfficialAccount(ctx context.Context, in *OfficialAccountRequest, opts ...grpc.CallOption) (*OfficialAccountReply, error) {
	out := new(OfficialAccountReply)
	err := c.cc.Invoke(ctx, OfficialAccount_GetOfficialAccount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OfficialAccountServer is the server API for OfficialAccount service.
// All implementations must embed UnimplementedOfficialAccountServer
// for forward compatibility
type OfficialAccountServer interface {
	GetOfficialAccount(context.Context, *OfficialAccountRequest) (*OfficialAccountReply, error)
	mustEmbedUnimplementedOfficialAccountServer()
}

// UnimplementedOfficialAccountServer must be embedded to have forward compatible implementations.
type UnimplementedOfficialAccountServer struct {
}

func (UnimplementedOfficialAccountServer) GetOfficialAccount(context.Context, *OfficialAccountRequest) (*OfficialAccountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOfficialAccount not implemented")
}
func (UnimplementedOfficialAccountServer) mustEmbedUnimplementedOfficialAccountServer() {}

// UnsafeOfficialAccountServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OfficialAccountServer will
// result in compilation errors.
type UnsafeOfficialAccountServer interface {
	mustEmbedUnimplementedOfficialAccountServer()
}

func RegisterOfficialAccountServer(s grpc.ServiceRegistrar, srv OfficialAccountServer) {
	s.RegisterService(&OfficialAccount_ServiceDesc, srv)
}

func _OfficialAccount_GetOfficialAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OfficialAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfficialAccountServer).GetOfficialAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OfficialAccount_GetOfficialAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfficialAccountServer).GetOfficialAccount(ctx, req.(*OfficialAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OfficialAccount_ServiceDesc is the grpc.ServiceDesc for OfficialAccount service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OfficialAccount_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.v1.OfficialAccount",
	HandlerType: (*OfficialAccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOfficialAccount",
			Handler:    _OfficialAccount_GetOfficialAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld.proto",
}
