---
--- Generated by Luanalysis
--- Created by blj.
--- DateTime: 2023/2/24 17:46
---

-- 1.table 关联数组
tab1 = { key1 = "val1", key2 = "val2", "val3" } -- 关联数组 一个key 有多个key 但是其他value 没有key
for k, v in pairs(tab1) do
    print(k .. " - " .. v)
    --print(k, v)
end
