Kafka:
  GaoDe:
    LingerMs: 100
    BatchSize: 100
    MaxMessageBytes: 1000000
    MaxRequestSize: 1000000
    Compression: snappy
    Acks: all
    Retries: 3
    RetryBackoffMs: 100
  Tencent:
    LingerMs: 100
    BatchSize: 100
    MaxMessageBytes: 1000000
    MaxRequestSize: 1000000
    Compression: snappy
    Acks: all
    Retries: 3
    RetryBackoffMs: 100
  BaiDu:
    LingerMs: 100
    BatchSize: 100
    MaxMessageBytes: 1000000
    MaxRequestSize: 1000000
    Compression: snappy
    Acks: all
    Retries: 3
    RetryBackoffMs: 100
