// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q               = new(Query)
	MiniOa          *miniOa
	MiniProgram     *miniProgram
	OfficialAccount *officialAccount
	WxUser          *wxUser
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	MiniOa = &Q.MiniOa
	MiniProgram = &Q.MiniProgram
	OfficialAccount = &Q.OfficialAccount
	WxUser = &Q.WxUser
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:              db,
		MiniOa:          newMiniOa(db, opts...),
		MiniProgram:     newMiniProgram(db, opts...),
		OfficialAccount: newOfficialAccount(db, opts...),
		WxUser:          newWxUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	MiniOa          miniOa
	MiniProgram     miniProgram
	OfficialAccount officialAccount
	WxUser          wxUser
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		MiniOa:          q.MiniOa.clone(db),
		MiniProgram:     q.MiniProgram.clone(db),
		OfficialAccount: q.OfficialAccount.clone(db),
		WxUser:          q.WxUser.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		MiniOa:          q.MiniOa.replaceDB(db),
		MiniProgram:     q.MiniProgram.replaceDB(db),
		OfficialAccount: q.OfficialAccount.replaceDB(db),
		WxUser:          q.WxUser.replaceDB(db),
	}
}

type queryCtx struct {
	MiniOa          IMiniOaDo
	MiniProgram     IMiniProgramDo
	OfficialAccount IOfficialAccountDo
	WxUser          IWxUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		MiniOa:          q.MiniOa.WithContext(ctx),
		MiniProgram:     q.MiniProgram.WithContext(ctx),
		OfficialAccount: q.OfficialAccount.WithContext(ctx),
		WxUser:          q.WxUser.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
