// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAccount = "account"

// Account mapped from table <account>
type Account struct {
	ID                    int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键Id" json:"id"`                                // 主键Id
	CreatedAt             *time.Time     `gorm:"column:created_at;type:datetime(3);comment:创建时间" json:"created_at"`                                         // 创建时间
	UpdatedAt             *time.Time     `gorm:"column:updated_at;type:datetime(3);comment:修改时间" json:"updated_at"`                                         // 修改时间
	DeletedAt             gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_account_deleted_at,priority:1;comment:删除时间" json:"deleted_at"` // 删除时间
	Version               *int64         `gorm:"column:version;type:bigint" json:"version"`
	UpdatedByID           *int64         `gorm:"column:updated_by_id;type:bigint;comment:操作账号Id" json:"updated_by_id"`                             // 操作账号Id
	UserName              *string        `gorm:"column:user_name;type:varchar(191);uniqueIndex:user_name,priority:1;comment:用户名" json:"user_name"` // 用户名
	Name                  *string        `gorm:"column:name;type:longtext;comment:用户名" json:"name"`                                                // 用户名
	Password              *string        `gorm:"column:password;type:longtext;comment:密码" json:"password"`                                         // 密码
	Phone                 *string        `gorm:"column:phone;type:varchar(191);uniqueIndex:phone,priority:1;comment:手机号" json:"phone"`             // 手机号
	Role                  *string        `gorm:"column:role;type:longtext;comment:角色" json:"role"`                                                 // 角色
	EnterpriseID          *string        `gorm:"column:enterprise_id;type:longtext;comment:集团id,主系统wid" json:"enterprise_id"`                      // 集团id,主系统wid
	SubsidiaryID          *int64         `gorm:"column:subsidiary_id;type:bigint;comment:所属4S店" json:"subsidiary_id"`                              // 所属4S店
	Valid                 *bool          `gorm:"column:valid;type:tinyint(1);comment:是否有效" json:"valid"`                                           // 是否有效
	Status                *int64         `gorm:"column:status;type:bigint;comment:账号状态，1=有效，2=无效" json:"status"`                                   // 账号状态，1=有效，2=无效
	ExportDesensitization *bool          `gorm:"column:export_desensitization;type:tinyint(1);comment:导出数据是否脱敏" json:"export_desensitization"`     // 导出数据是否脱敏
}

// TableName Account's table name
func (*Account) TableName() string {
	return TableNameAccount
}
