// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMiniOa = "mini_oa"

// MiniOa mapped from table <mini_oa>
type MiniOa struct {
	ID     int64 `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键Id" json:"id"` // 主键Id
	MiniID int64 `gorm:"column:mini_id;type:bigint;not null" json:"mini_id"`
	OaID   int64 `gorm:"column:oa_id;type:bigint;not null" json:"oa_id"`
}

// TableName MiniOa's table name
func (*MiniOa) TableName() string {
	return TableNameMiniOa
}
