// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOperatorLog = "operator_logs"

// OperatorLog mapped from table <operator_logs>
type OperatorLog struct {
	ID             int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键Id" json:"id"`                             // 主键Id
	CreatedAt      *time.Time     `gorm:"column:created_at;type:datetime(3);comment:创建时间" json:"created_at"`                                      // 创建时间
	UpdatedAt      *time.Time     `gorm:"column:updated_at;type:datetime(3);comment:修改时间" json:"updated_at"`                                      // 修改时间
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);comment:删除时间" json:"deleted_at"`                                      // 删除时间
	OperatorType   *string        `gorm:"column:operator_type;type:varchar(255);comment:操作类型" json:"operator_type"`                               // 操作类型
	UserID         int64          `gorm:"column:user_id;type:bigint;not null;index:fk_operation_user_id,priority:1;comment:操作人ID" json:"user_id"` // 操作人ID
	OperatorDetail *string        `gorm:"column:operator_detail;type:varchar(255);comment:操作详情" json:"operator_detail"`                           // 操作详情
	FileDesensity  *bool          `gorm:"column:file_desensity;type:tinyint(1);comment:文件是否脱敏" json:"file_desensity"`                             // 文件是否脱敏
}

// TableName OperatorLog's table name
func (*OperatorLog) TableName() string {
	return TableNameOperatorLog
}
