// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOperateLog = "operate_log"

// OperateLog mapped from table <operate_log>
type OperateLog struct {
	ID              int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键Id" json:"id"`                                      // 主键Id
	CreatedAt       *time.Time     `gorm:"column:created_at;type:datetime(3);comment:创建时间" json:"created_at"`                                               // 创建时间
	UpdatedAt       *time.Time     `gorm:"column:updated_at;type:datetime(3);comment:修改时间" json:"updated_at"`                                               // 修改时间
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);comment:删除时间" json:"deleted_at"`                                               // 删除时间
	OperateType     *string        `gorm:"column:operate_type;type:varchar(255);comment:操作类型" json:"operate_type"`                                          // 操作类型
	AccountID       int64          `gorm:"column:account_id;type:bigint;not null;index:fk_operation_account_id,priority:1;comment:操作人ID" json:"account_id"` // 操作人ID
	OperateDetail   *string        `gorm:"column:operate_detail;type:varchar(255);comment:操作详情" json:"operate_detail"`                                      // 操作详情
	FileDesensitize *bool          `gorm:"column:file_desensitize;type:tinyint(1);comment:文件是否脱敏" json:"file_desensitize"`                                  // 文件是否脱敏
	FileName        *string        `gorm:"column:file_name;type:varchar(255);comment:文件名称" json:"file_name"`                                                // 文件名称
	ExportStatus    *bool          `gorm:"column:export_status;type:tinyint(1);comment:导出状态" json:"export_status"`                                          // 导出状态
}

// TableName OperateLog's table name
func (*OperateLog) TableName() string {
	return TableNameOperateLog
}
