// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRoleMenu = "role_menu"

// RoleMenu mapped from table <role_menu>
type RoleMenu struct {
	ID        int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键Id" json:"id"`                                  // 主键Id
	CreatedAt *time.Time     `gorm:"column:created_at;type:datetime(3);comment:创建时间" json:"created_at"`                                           // 创建时间
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:datetime(3);comment:修改时间" json:"updated_at"`                                           // 修改时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_role_menu_deleted_at,priority:1;comment:删除时间" json:"deleted_at"` // 删除时间
	Role      *string        `gorm:"column:role;type:varchar(191);index:idx_role_menu_role,priority:1;comment:角色" json:"role"`                    // 角色
	Key       *string        `gorm:"column:key;type:varchar(191);index:idx_role_menu_key,priority:1;comment:菜单唯一标志" json:"key"`                   // 菜单唯一标志
	Label     *string        `gorm:"column:label;type:varchar(191);index:idx_role_menu_label,priority:1;comment:菜单名称label" json:"label"`          // 菜单名称label
	Icon      *string        `gorm:"column:icon;type:varchar(191);index:idx_role_menu_icon,priority:1;comment:菜单icon" json:"icon"`                // 菜单icon
	Sort      *int64         `gorm:"column:sort;type:bigint;index:idx_role_menu_sort,priority:1;comment:排序" json:"sort"`                          // 排序
	Path      *string        `gorm:"column:path;type:longtext;comment:页面路由" json:"path"`                                                          // 页面路由
}

// TableName RoleMenu's table name
func (*RoleMenu) TableName() string {
	return TableNameRoleMenu
}
