version: "3"



services:
  # "47.107.47.161" public
  # "172.18.102.68" private
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    volumes:
      - ./loki.yaml:/etc/loki.yaml
    #      - ./loki/index:/opt/loki/index
    #      - ./loki/chunks:/opt/loki/chunks
    #      - ./loki/wal:/wal
    #    command: -config.file=/etc/loki.yaml
    command: -config.file=/etc/loki/local-config.yaml
#    logging:
#      driver: loki
#      options:
#        loki-url: 'http://47.107.47.161:3100/api/prom/push'

  tempo:
    image: grafana/tempo:2.2.1
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - "14268:14268"  # jaeger ingest
      - "3200:3200"    # tempo
      - "9095:9095"    # tempo grpc
      - "4317:4317"    # otlp grpc
      - "4318:4318"    # otlp http
      - "9411:9411"    # zipkin

  prometheus:
    image: prom/prometheus:v2.46.0
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.1.0
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    logging:
      driver: loki
      options:
        loki-url: 'http://47.107.47.161:3100/api/prom/push'
