global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ '172.18.102.68:9090' ]
  - job_name: 'tempo'
    static_configs:
      - targets: [ '172.18.102.68:3200' ]
