version: "3"

services:
  # "47.107.47.161" public
  # "172.18.102.68" private
  loki:
    image: grafana/loki:2.2.0
    container_name: loki
    command: -config.file=/etc/loki.yaml
    volumes:
      - ./loki.yaml:/etc/loki.yaml
      - /data/loki/index:/opt/loki/index
      - data/loki/chunks:/opt/loki/chunks
    ports:
      - "3100:3100"
    logging:
      driver: loki
      options:
        loki-url: 'http://47.107.47.161:3100/api/prom/push'


