// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameStudent = "students"

// Student mapped from table <students>
type Student struct {
	ID   int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name string `gorm:"column:name" json:"name"`
	Age  int64  `gorm:"column:age" json:"age"`
}

// TableName Student's table name
func (*Student) TableName() string {
	return TableNameStudent
}
